### ISSUE TITLE
--all-in-meta not getting module version?

### ISSUE THREAD

**Issue by xenoterracide** [AndyA/CPAN--Mini--Inject#13]
`Required option not specified: module version at /home/gpan/perl5/bin/mcpani line 102`

here's my META.yml

```

---
abstract: MyPanTest
author:
  - 'Caleb Cushing <xenoterracide@gmail.com>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112621'
license: restrictive
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MyPanTest
no_index:
  file:
    - perlcritic.rc
requires:
  autodie: 0
  perl: 5.014
  strict: 0
  utf8::all: 0
  warnings: 0
resources: {}
version: v0.1.0
```
